title: "Sibonelo Mazibuko"
logo: /assets/head&shoulders.png
description: Computer Science Student | Data Science Enthusiast
theme: jekyll-theme-minimal
google_analytics: UA-XXXXXXXXX-X
show_downloads: false
