title: "Sibonelo Mazibuko"
logo: /assets/head&shoulders.png
description: Computer Science Student | Data Science Enthusiast
theme: minimal-mistakes
navigation:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /#projects
  - title: "Contact"
    url: /#contact
google_analytics: UA-XXXXXXXXX-X
show_downloads: false
